-- Enable RLS on api tables
ALTER TABLE api.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE api.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE api.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE api.balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE api.currencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE api.exchange_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE secret.keys ENABLE ROW LEVEL SECURITY;