include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - prefer_const_constructors
    - prefer_const_declarations
    - directives_ordering
    - sort_child_properties_last
    - always_use_package_imports
    - sized_box_for_whitespace
    - no_logic_in_create_state
    - use_key_in_widget_constructors
    - require_trailing_commas
    - cascade_invocations
    - always_declare_return_types
    - avoid_init_to_null
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - empty_catches
    - exhaustive_cases
    - empty_statements
    - no_duplicate_case_values
    - prefer_typing_uninitialized_variables
    - package_names
    - avoid_web_libraries_in_flutter
    - curly_braces_in_flow_control_structures
    - unawaited_futures
    - avoid_catches_without_on_clauses
    - only_throw_errors
    - prefer_foreach
    - avoid_classes_with_only_static_members
    - prefer_void_to_null
    - prefer_asserts_with_message
    - prefer_final_locals
    - use_rethrow_when_possible
    - prefer_final_in_for_each
    - avoid_unnecessary_containers
    - prefer_if_elements_to_conditional_expressions
    - unnecessary_await_in_return
    - unnecessary_unawaited
    - await_only_futures
    - empty_constructor_bodies
    - file_names
    - implementation_imports
    - null_check_on_nullable_type_parameter
    - use_raw_strings

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    unawaited_futures: error
  exclude:
    - 'build/**'
    - 'android/**'
    - 'ios/**'
    - 'test/**'
    - ".dart_tool/**"
    - "assets/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"