name: pocketa
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^16.0.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  freezed: ^3.1.0
  freezed_lint: ^0.0.10
  json_serializable: ^6.9.5
  
flutter:
  uses-material-design: true
